-- AlterTable
ALTER TABLE "User" ADD COLUMN     "jobSuccessScore" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "rating" DECIMAL(65,30) NOT NULL DEFAULT 0.0,
ADD COLUMN     "reviewCount" INTEGER NOT NULL DEFAULT 0;
